#!/usr/bin/env python3
"""R6 — Generate locomotion logs and figures for publication.

Produces:
    1. sim_torso6d_log.json   — single-step MPC (already generated by sim_torso6d.py)
    2. sim_lutze_log.json     — single-step Lutze baseline (already generated by sim_lutze.py)
    3. r6_multistep_log.json  — multi-step MPC (3 steps, closed-loop)
    4. comparison.png         — Lutze vs MPC single-step comparison
    5. r6_multistep_7panel.png — multi-step 7-panel diagnostic
    6. Prints a summary table of all metrics for the paper.

Usage:
    PYTHONPATH=. MUJOCO_GL=disabled python3 run_r6_full_sim.py
"""
import os
import sys
import time
import numpy as np

_root = os.path.join(os.path.dirname(__file__), '..')
sys.path.insert(0, _root)
os.environ.setdefault('MUJOCO_GL', 'disabled')

from simulation_loop import SimulationLoop, SimConfig, SimLog

URDF = os.path.join(_root, 'models', 'VISPA_crawling_fixed.urdf')
MJCF = os.path.join(_root, 'models', 'VISPA_crawling.xml')


def run_multistep():
    """Run multi-step MPC simulation and return log."""
    print('=' * 70)
    print('  R6 — Multi-step MPC simulation (n_steps=3)')
    print('=' * 70)
    sim = SimulationLoop(mjcf_path=MJCF, urdf_path=URDF)
    sim.setup(n_steps=3, start_a=2, start_b=2)
    t0 = time.time()
    log = sim.run(verbose=True)
    wall = time.time() - t0
    print(f'\n  Wall time: {wall:.1f}s, {len(log.t)} NMPC steps logged')
    return log


def run_single_step_mpc():
    """Run single-step MPC simulation and return log dict."""
    print('\n' + '=' * 70)
    print('  R6 — Single-step MPC simulation')
    print('=' * 70)
    # Import and run sim_torso6d as a module
    import sim_torso6d
    sys.argv = ['sim_torso6d', '--urdf', URDF, '--mjcf', MJCF]
    # sim_torso6d writes sim_torso6d_log.json on execution
    exec(open(os.path.join(_root, 'scripts', 'sim_torso6d.py')).read(), {'__name__': '__run__'})
    return SimLog.load(os.path.join(_root, 'results', 'logs', 'sim_torso6d_log.json'))


def run_lutze_baseline():
    """Run Lutze baseline simulation and return log dict."""
    print('\n' + '=' * 70)
    print('  R6 — Lutze baseline simulation')
    print('=' * 70)
    sys.argv = ['sim_lutze', '--urdf', URDF, '--mjcf', MJCF]
    exec(open(os.path.join(_root, 'lutze_baseline', 'sim_lutze.py')).read(), {'__name__': '__run__'})
    return SimLog.load(os.path.join(_root, 'results', 'logs', 'sim_lutze_log.json'))


def print_summary(log_multi, log_mpc_path, log_lutze_path):
    """Print publication-ready summary table."""
    import json
    with open(log_mpc_path) as f:
        log_mpc = json.load(f)
    with open(log_lutze_path) as f:
        log_lutze = json.load(f)

    print('\n' + '=' * 70)
    print('  R6 — Summary for Publication')
    print('=' * 70)

    # Multi-step metrics
    t = np.array(log_multi.t)
    Ln = np.array(log_multi.L_com_norm)
    tau_max = log_multi.tau_max_joint
    n_dock = len(log_multi.dock_events)
    n_steps = len(log_multi.t)
    n_nmpc_fail = sum(1 for x in log_multi.nmpc_ok if not x)
    n_qp_fail = sum(1 for x in log_multi.qp_ok if not x)
    struct_drift = np.linalg.norm(
        np.array(log_multi.struct_pos[-1]) - np.array(log_multi.struct_pos[0]))

    print(f'\n  {"Metric":<35} {"Multi-step (3)":<18} {"MPC (1-step)":<18} {"Lutze (1-step)"}')
    print(f'  {"-"*35} {"-"*18} {"-"*18} {"-"*18}')

    # Docking
    dock_dists = [f'{e["d_mm"]:.1f}mm' for e in log_multi.dock_events]
    mpc_dock = f'{min(np.array(log_mpc["d_grip_b"]))*1000:.1f}mm'
    lutze_dock = f'{min(np.array(log_lutze["d_grip_b"]))*1000:.1f}mm'
    print(f'  {"Docks achieved":<35} {n_dock}/3{"":<14} {"1/1":<18} {"1/1"}')
    print(f'  {"Dock distances":<35} {", ".join(dock_dists):<18}')
    print(f'  {"Min grip distance":<35} {"":<18} {mpc_dock:<18} {lutze_dock}')

    # Momentum
    L_mpc = np.linalg.norm(np.array(log_mpc['L_com']), axis=1) if 'L_com' in log_mpc else [0]
    L_lutze = np.linalg.norm(np.array(log_lutze['L_com']), axis=1) if 'L_com' in log_lutze else [0]
    print(f'  {"Peak ||L_com|| [Nms]":<35} {max(Ln):<18.2f} {max(L_mpc):<18.2f} {max(L_lutze):.2f}')
    print(f'  {"Mean ||L_com|| [Nms]":<35} {np.mean(Ln):<18.2f} {np.mean(L_mpc):<18.2f} {np.mean(L_lutze):.2f}')

    # Torques
    tau_mpc_max = max(log_mpc['tau_max_joint'])
    tau_lutze_max = max(log_lutze['tau_max_joint'])
    print(f'  {"Peak |tau| [Nm]":<35} {max(tau_max):<18.2f} {tau_mpc_max:<18.2f} {tau_lutze_max:.2f}')

    # Drift
    sp_mpc = np.array(log_mpc['struct_pos'])
    sp_lutze = np.array(log_lutze['struct_pos'])
    drift_mpc = np.linalg.norm(sp_mpc[-1] - sp_mpc[0])
    drift_lutze = np.linalg.norm(sp_lutze[-1] - sp_lutze[0])
    print(f'  {"Structure drift [cm]":<35} {struct_drift*100:<18.1f} {drift_mpc*100:<18.1f} {drift_lutze*100:.1f}')

    # Solver health
    print(f'  {"NMPC fail rate":<35} {n_nmpc_fail}/{n_steps} ({n_nmpc_fail/n_steps*100:.1f}%)')
    print(f'  {"QP fail rate":<35} {n_qp_fail}/{n_steps} ({n_qp_fail/n_steps*100:.1f}%)')

    # Sim duration
    print(f'  {"Sim duration [s]":<35} {t[-1]:<18.1f} {np.array(log_mpc["t"])[-1]:<18.1f} {np.array(log_lutze["t"])[-1]:.1f}')


if __name__ == '__main__':
    _logs = os.path.join(_root, 'results', 'logs')
    _figs = os.path.join(_root, 'results', 'figures')
    os.makedirs(_logs, exist_ok=True)
    os.makedirs(_figs, exist_ok=True)

    # 1. Multi-step MPC
    log_multi = run_multistep()
    log_multi.save(os.path.join(_logs, 'r6_multistep_log.json'))
    print('  Saved: results/logs/r6_multistep_log.json')

    # 2. Generate multi-step 7-panel figure
    SimulationLoop.plot(log_multi, save_path=os.path.join(_figs, 'r6_multistep_7panel.png'))
    print('  Saved: results/figures/r6_multistep_7panel.png')

    # 3. Summary table (uses existing single-step logs)
    mpc_log = os.path.join(_logs, 'sim_torso6d_log.json')
    lutze_log = os.path.join(_logs, 'sim_lutze_log.json')
    if os.path.exists(mpc_log) and os.path.exists(lutze_log):
        print_summary(log_multi, mpc_log, lutze_log)
    else:
        print('\n  [INFO] Run sim_torso6d.py and sim_lutze.py first for comparison data')

    print('\n' + '=' * 70)
    print('  R6 complete. Output files:')
    print('    - results/logs/r6_multistep_log.json')
    print('    - results/figures/r6_multistep_7panel.png')
    print('=' * 70)
