#!/usr/bin/env python3
"""M7 v21: pre-planner CoM cruise-box + v19 quintic arm interp.

Configuration
-------------
- CoarsePrePlanner: adds a cruise-phase acceleration constraint on the
  CoM trajectory. For knots k ∈ [0.2·M, 0.8·M] the pre-planner
  enforces ||a_com(k)|| ≤ a_cruise_max (here 0.01 m/s²) via a bound on
  ||f_stance(k)||² ≤ (m·a_cruise_max)². This produces a trapezoidal
  CoM velocity profile: accelerate early, cruise (a_com ≈ 0) mid-step,
  decelerate late.
- TorsoPlanner: quintic profile (restored from v18). The SS linear
  torso reference is produced by the mapping r_b = (M/m_b)·r_com −
  δ(q)/m_b, so the shaped CoM trajectory flows through into the QP's
  torso linear task; angular reference still comes from the planner.
- Mapping: active in SS and DS with planned-δ (v19).
- EE task-consistent feedforward (v17) active in wholebody_qp.py.
- All other settings from v19 unchanged: alpha_wrench=0.01,
  alpha_com_soft=0.0, weight_ratio=1.0, 7-DOF arms, quintic
  SwingPlanner.

Rationale (M7 technical log, v20 → v21)
- v20 shaped the torso planner (trapezoidal 20/60/20) but the SS
  linear reference is generated by the mapping, not the torso planner,
  so the shaping had no effect on the tracking task.
- v21 moves the shaping to the **pre-planner CoM trajectory** — the
  upstream signal that the mapping actually consumes as r_com_ref /
  v_com_ref. Cruise-phase a_com ≈ 0 means the mapping's acceleration
  demand during the cruise is dominated by δ̈(q, dq, ddq), which is
  small for a smooth arm swing, freeing the joint-torque budget for
  the EE task.

Output: Misc/runs/M7_1pct_1step_v21/.
"""
from __future__ import annotations

import os
import sys

_root = os.path.join(os.path.dirname(__file__), '..')
sys.path.insert(0, _root)
os.environ.setdefault('MUJOCO_GL', 'disabled')

import scripts.run_m7_single_step as r


if __name__ == '__main__':
    cfg = r._make_m7_config()
    # v21: enable the pre-planner CoM cruise-phase acceleration box.
    cfg.preplanner_a_cruise_max = 0.01      # [m/s²] cruise accel cap
    cfg.preplanner_cruise_ramp_frac = 0.2   # 20/60/20 split
    r.run_case(
        '1pct 1-step v21 (preplanner a_cruise_max=0.01 + quintic + planned-delta + EE FF)',
        'Misc/runs/M7_1pct_1step_v21', n_steps=1, config=cfg)
